config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :kato_rooms
  root  'homes#index'

end

app/models/kato_room.rb
class KatoRoom 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  # GET /homes
  # GET /homes.json
  def index
    
    @php =File.read('./PHP/index.php')
    @phphtml =File.read('./PHP/template.html')
    
    @node = File.read('./nodejs/app.js')
    @nodehtml = File.read('./nodejs/index.html')
   
    @net = File.read('./net/JWT.cs')
    @nethtml = File.read('./net/index.html')
   
    @ror = File.read('./ror/JWT.rb')
    @rorhtml = File.read('./ror/index.html')
    
    @django = File.read('./python/views.py')
    @djangohtml = File.read('./python/katoTemplate.html')
    
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_home
    @home = Home.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def home_params
    params[:home]
  end
end

app/controllers/kato_rooms_controller.rb
class KatoRoomsController < ApplicationController
  before_action :set_kato_room, only: [:show, :edit, :update, :destroy]
  # GET /kato_rooms
  # GET /kato_rooms.json
  def index

    @url =KatoAdHocExpress.setInfo( response, "EMxxK0z32ULskJgTKlgrouB6C9fDIjkXq92UPb1ICwk",3600, "1", "foo", "1", "bar")
    
    respond_to do |format|
      format.html {render action: "index"}
      format.json {render json: { "JWTToken" => @url}}
    end
  end

  # GET /kato_rooms/1
  # GET /kato_rooms/1.json
  def show
  end

  # GET /kato_rooms/new
  def new
    @kato_room = KatoRoom.new
  end

  # GET /kato_rooms/1/edit
  def edit
  end

  # POST /kato_rooms
  # POST /kato_rooms.json
  def create
    @kato_room = KatoRoom.new(kato_room_params)

    respond_to do |format|
      if @kato_room.save
        format.html { redirect_to @kato_room, notice: 'Kato room was successfully created.' }
        format.json { render :show, status: :created, location: @kato_room }
      else
        format.html { render :new }
        format.json { render json: @kato_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kato_rooms/1
  # PATCH/PUT /kato_rooms/1.json
  def update
    respond_to do |format|
      if @kato_room.update(kato_room_params)
        format.html { redirect_to @kato_room, notice: 'Kato room was successfully updated.' }
        format.json { render :show, status: :ok, location: @kato_room }
      else
        format.html { render :edit }
        format.json { render json: @kato_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kato_rooms/1
  # DELETE /kato_rooms/1.json
  def destroy
    @kato_room.destroy
    respond_to do |format|
      format.html { redirect_to kato_rooms_url, notice: 'Kato room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_kato_room
    @kato_room = KatoRoom.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def kato_room_params
    params.require(:kato_room).permit(:Get)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/kato_rooms_helper.rb
module KatoRoomsHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
		<input id="aspCodeRaw" type="hidden" value="<%= @net %>" />
		<input id="aspHtmlRaw" type="hidden" value="<%= @nethtml %><" />
		
		<input id="phpCodeRaw" type="hidden" value="<%= @php %>" />
		<input id="phpHtmlRaw" type="hidden" value="<%= @phphtml %>" />
		
		<input id="rubyCodeRaw" type="hidden" value="<%= @ror %>" />
		<input id="rubyHtmlRaw" type="hidden" value="<%= @rorhtml %><" />
		
		<input id="djangoCodeRaw" type="hidden" value="<%= @django %>" />
		<input id="djangoHtmlRaw" type="hidden" value="<%= @djangohtml %><" />
		
		<input id="nodeCodeRaw" type="hidden" value="<%= @node %>" />
		<input id="nodeHtmlRaw" type="hidden" value="<%= @nodehtml %><" />
		
		<div class="container">
			<h1>Kato Adhoc Room code snippets</h1>
			<br />
			<form class="form-horizontal">
				<div class="control-group">
					<label class="control-label">Secret Key</label>
					<div class="controls">
						<input type="text" id="skey" placeholder="Secret Key">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">Public Key</label>
					<div class="controls">
						<input type="text" id="pkey" placeholder="Public Key">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">User ID</label>
					<div class="controls">
						<input type="text" id="userid" placeholder="User ID">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">User Name</label>
					<div class="controls">
						<input type="text" id="username" placeholder="User Name">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">Room ID</label>
					<div class="controls">
						<input type="text" id="roomid" placeholder="Room ID">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">Room Name</label>
					<div class="controls">
						<input type="text" id="roomname" placeholder="Room Name">
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">Session Duration</label>
					<div class="controls">
						<input type="text" id="duration" placeholder="Session Duration">
					</div>
				</div>
			</form>


		<h2>Choose Language</h2>
		<br />
		<ul class="nav nav-tabs" id="tabs">
				<li class="active">
					<a href="#AspNet" class="aspNet">Asp NET</a>
				</li>
				<li>
					<a href="#php" class="php">PHP</a>
				</li>
				<li>
					<a href="#ruby" class="ruby">Ruby On Rails</a>
				</li>
				<li>
					<a href="#django" class="django">Django Phyton</a>
				</li>
				<li>
					<a href="#nodeJS" class="nodeJS">NodeJS</a>
				</li>
			</ul>
		
		<br />
			<div class="tabs" id="aspNet">
				<div class="alert alert-info"><b>Instructions:</b> Install nuget package <i>"Install-Package KatoAdhocExpress"</i></div>
				<h4>Asp.NET Code:</h4>
				<pre>
					<code></code>
				</pre>
				<h4>Html:</h4>
				<pre>
					<code id="aspNetHtml"></code>
				</pre>
			</div>

			<div class="tabs" id="php">
				<div class="alert alert-info"><b>Instructions:</b> Download JWT class from <a target="_new" href="https://github.com/cfrett/JWT-PHP/blob/master/JWT.php">"https://github.com/cfrett/JWT-PHP/blob/master/JWT.php</a></i></div>
				<h4>Php Code:</h4>
				<pre>
					<code></code>
				</pre>
				<h4>Html:</h4>
				<pre>
					<code id="phpHtml"></code>
				</pre>
			</div>
			<div class="tabs" id="ruby">
				<div class="alert alert-info"><b>Instructions:</b> Install GEM package <i>"gem install katoadhocexpress"</i></div>
				<h4>Ruby Code:</h4>
				<pre>
					<code></code>
				</pre>
				<h4>Html:</h4>
				<pre>
					<code id="rubyHtml"></code>
				</pre>
			</div>
			<div class="tabs" id="django">
				<div class="alert alert-info"><b>Instructions:</b> Install package <i>"pip install KatoAdhocExpress"</i></div>
				<h4>Phyton (Django) Code:</h4>
				<pre>
					<code></code>
				</pre>
				<h4>Html:</h4>
				<pre>
					<code id="djangoHtml"></code>
				</pre>
			</div>
			<div class="tabs" id="nodeJS">
				<div class="alert alert-info"><b>Instructions:</b> Install package <i>"npm install kato-adhoc-express</i></div>
				<h4>NodeJS Code:</h4>
				<pre>
					<code></code>
				</pre>
				<h4>Html:</h4>
				<pre>
					<code id="nodeJSHtml"></code>
				</pre>
			</div>

		
	
	

	<style type="text/css">
			.tabs{
				display:none;
			}
			.container input{
				padding:13px !important;
			}
		</style>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/kato_rooms/_form.html.erb
<%= form_for(@kato_room) do |f| %>
  <% if @kato_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kato_room.errors.count, "error") %> prohibited this kato_room from being saved:</h2>

      <ul>
      <% @kato_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Get %><br>
    <%= f.text_field :Get %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kato_rooms/edit.html.erb
<h1>Editing kato_room</h1>

<%= render 'form' %>

<%= link_to 'Show', @kato_room %> |
<%= link_to 'Back', kato_rooms_path %>

app/views/kato_rooms/index.html.erb
<body>
    <p>Hello friend</p>
    <script type="text/javascript">
        var katoAdhocReadCookie = function () {
            var nameEQ = 'KATO_ADHOC_TOKEN' + '=';
            var ca = document.cookie.split(';');
            for(var i=0;i < ca.length;i++) {
                var c = ca[i];
                while (c.charAt(0)==' ') c = c.substring(1,c.length);
                if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
            }
            return null;
        }
        var katoContainer = document.createElement('div');
        katoContainer.id = 'katoContainer';
        katoContainer.style.display = 'block';
        katoContainer.style.position = 'fixed';
        katoContainer.style.right = '20px';
        katoContainer.style.bottom = '0px';
        katoContainer.style['background-color'] = '#fcfcfc';
        katoContainer.style.border = '10px solid #fcfcfc';

        katoContainer.innerHTML = "<a style='font-weight: bold; font-family: Verdana, Arial, Helvetica, sans-serif; color: #666666; text-decoration: none; float: right; clear: both; margin-bottom: 10px;' id='katoButton' href='#' onclick='toggleKatoRoom();'>Support</a><div id='katoContainerInner' style='display: none;'><iframe style='height:350px;' frameBorder='0' src='http://app.kato.im/adhoc#/dychNluc2WxxX46N-odG3aOBxF_h4o39P_y3eNZf7Pc/" + katoAdhocReadCookie() + "'></iframe></div>";
        document.body.appendChild(katoContainer);

        var toggleKatoRoom = function () {
            var el = document.getElementById('katoButton');
            var iframeContainer = document.getElementById('katoContainerInner');
            if (iframeContainer.style.display === 'none') {
                el.innerHTML = 'Hide';
                iframeContainer.style.display = 'block'
            } else {
                el.innerHTML = 'Support';
                iframeContainer.style.display = 'none'
            }
        };
    </script>
</body>

app/views/kato_rooms/new.html.erb
<h1>New kato_room</h1>

<%= render 'form' %>

<%= link_to 'Back', kato_rooms_path %>

app/views/kato_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Get:</strong>
  <%= @kato_room.Get %>
</p>

<%= link_to 'Edit', edit_kato_room_path(@kato_room) %> |
<%= link_to 'Back', kato_rooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KatoAdhoc</title>
  <%= csrf_meta_tags %>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>